---
version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_SUPER_SECRET_PASSWORD
      MYSQL_DATABASE: snipeit
      MYSQL_USER: snipeit
      MYSQL_PASSWORD: YOUR_SUPER_SECRET_PASSWORD

  snipe:
    image: snipe/snipe-it:v4.6.13
    volumes:
      - ./snipe-it-data:/var/lib/snipeit
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "8000:80"
      - "8443:443"
    restart: always
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:GpR8YlKxmKJDtiX+/uYdF0IevTQ1zjHrSH/GI5/bxxI=
      APP_URL: http://127.0.0.1:80
      APP_TIMEZONE: US/Pacific
      APP_LOCALE: en
      MYSQL_ROOT_PASSWORD: YOUR_SUPER_SECRET_PASSWORD
      MYSQL_DATABASE: snipeit
      MYSQL_USER: snipeit
      MYSQL_PASSWORD: YOUR_SUPER_SECRET_PASSWORD
      # Email Parameters
      # - the hostname/IP address of your mailserver
      MAIL_PORT_587_TCP_ADDR: smtp.whatever.com
      #the port for the mailserver (probably 587, could be another)
      MAIL_PORT_587_TCP_PORT: 587
      # the default from address, and from name for emails
      MAIL_ENV_FROM_ADDR: youremail@yourdomain.com
      MAIL_ENV_FROM_NAME: Your Full Email Name
      # - pick 'tls' for SMTP-over-SSL, 'tcp' for unencrypted
      MAIL_ENV_ENCRYPTION: tcp
      # SMTP username and password
      MAIL_ENV_USERNAME: your_email_username
      MAIL_ENV_PASSWORD: your_email_password
      DB_HOST: db


#https://snipe-it.readme.io/docs/docker


